# version du format de docker-compose (optionnel)
# on définit les services qui composent notre application = les conteneurs qui seront lancés
services:
  db:
    image: postgres:15 # image officielle de PostgreSQL version 15 depuis Docker Hub
    restart: always # redémarre le conteneur en cas de plantage ou redémarrage du système
    environment: # variables d'environnement pour configurer PostgreSQL
      POSTGRES_USER: ${POSTGRES_USER} # nom d'utilisateur pour la base de données
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # mot de passe pour l'utilisateur
      POSTGRES_DB: ${POSTGRES_DB} # nom de la base de données à créer
    ports:
      - "${POSTGRES_PORT}:5432" # port_pc:port_conteneur pour accéder à PostgreSQL depuis l'extérieur du conteneur
    volumes:
      - postgres_data:/var/lib/postgresql/data # Docker sauvegarde les données dans un volume nommé postgres_data

volumes:
  postgres_data : # définition du volume pour PostgreSQL
