# version du format de docker-compose (optionnel)
# on définit les services qui composent notre application = les conteneurs qui seront lancés
services:
  db:
    image: postgres:15 # image officielle de PostgreSQL version 15 depuis Docker Hub
    environment: # variables d'environnement pour configurer PostgreSQL
      POSTGRES_USER: budgetmeal # nom d'utilisateur pour la base de données
      POSTGRES_PASSWORD: budgetmeal # mot de passe pour l'utilisateur
      POSTGRES_DB: budgetmeal # nom de la base de données à créer
    ports:
      - "5432:5432" # port_pc:port_conteneur pour accéder à PostgreSQL depuis l'extérieur du conteneur
    volumes:
      - postgres_data:/var/lib/postgresql/data # Docker sauvegarde les données dans un volume nommé postgres_data

volumes:
  postgres_data : # définition du volume pour PostgreSQL
